services:
  toolbox:
    # TODO: It is recommended to pin to a specific image version instead of latest.
    image:  us-central1-docker.pkg.dev/database-toolbox/toolbox/toolbox:0.2.0
    container_name: business_assistant_toolbox
    hostname: toolbox
    platform: linux/amd64
    ports:
      - "5000:5000"
    volumes:
      - ./config:/config
    command: [ "toolbox", "--tools_file", "/config/tools.yaml", "--address", "0.0.0.0"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - business-assistant-network
  db:
    # TODO: It is recommended to pin to a specific image version instead of latest.
    image: postgres:15
    container_name: business_assistant_db
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: business_assistant_db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d business_assistant_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - business-assistant-network
networks:
  business-assistant-network:
