FROM us-central1-docker.pkg.dev/database-toolbox/toolbox/toolbox:0.2.0

# Copy our template tools.yaml
COPY config/tools.yaml /config/tools.yaml

# Set environment variables with default values
ENV POSTGRES_HOST=db \
    POSTGRES_PORT=5432 \
    POSTGRES_DB=business_assistant_db \
    POSTGRES_USER=postgres \
    POSTGRES_PASSWORD=postgres

# The toolbox image already has an ENTRYPOINT defined
# We don't need to override it
