name: Python CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt
      - name: Debug environment
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory listing:"
          ls -la
          echo "Python sys.path:"
          python -c "import sys; print(sys.path)"
          echo "Module structure:"
          python -c "import pkgutil; print([p for p in pkgutil.iter_modules()])"
      - name: Run tests
        run: |
          pytest -v
        env:
          PYTHONPATH: ${{ github.workspace }}/src
