name: Python Poetry Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install --no-root
      - name: Debug environment
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory listing:"
          ls -la
          echo "Python sys.path:"
          poetry run python -c "import sys; print(sys.path)"
          echo "Module structure:"
          poetry run python -c "import pkgutil; print([p for p in pkgutil.iter_modules()])"
      - name: Run tests
        run: |
          poetry run pytest -v
        env:
          PYTHONPATH: ${{ github.workspace }}
